### ISSUE TITLE
为什么要替换语雀的图片链接？

### ISSUE THREAD

**Issue by TomatoFryEggs** [labulaka521/yuque_sync#2]

**Comment by labulakalia** [comment]
语雀的图片链接有盗链检测所以我替换成本地的了

**Comment by TomatoFryEggs** [comment]
> 语雀的图片链接有盗链检测所以我替换成本地的了

可以解决的，参考这个。
https://github.com/x-cold/yuque-hexo/issues/41

**Comment by labulakalia** [comment]
感觉这个不是长久之计
我先康康这个

**Comment by TomatoFryEggs** [comment]
> 感觉这个不是长久之计
> 我先康康这个

嗯，你下下来也是个好办法。
