### ISSUE TITLE
请问如何不同步草稿文章？

### ISSUE THREAD

**Issue by TomatoFryEggs** [labulaka521/yuque_sync#3]

**Comment by labulakalia** [comment]
可以说详细点吗
我的理解是你想如果在在语雀中写了一些还未完成的文章，暂时不想发表，如果是这样你可以再设置wenhook的时候选择 仅主动推送更新触发  然后保存文章的时候如果文章已经完成可以点击下面那个按钮 文档有较大更新，推送给关注知识库的人，如果文章还未完成就别选择这个按钮就可以了

**Comment by TomatoFryEggs** [comment]
> 可以说详细点吗
> 我的理解是你想如果在在语雀中写了一些还未完成的文章，暂时不想发表，如果是这样你可以再设置wenhook的时候选择 仅主动推送更新触发 然后保存文章的时候如果文章已经完成可以点击下面那个按钮 文档有较大更新，推送给关注知识库的人，如果文章还未完成就别选择这个按钮就可以了

使用yuque_sync命令后会同步所有的文章，包含未发表的文章。

**Comment by labulakalia** [comment]
第一次运行会先同步这个知识库所有的文章

**Comment by TomatoFryEggs** [comment]
> 第一次运行会先同步这个知识库所有的文章

> 第一次运行会先同步这个知识库所有的文章

只是第一次么？如果我删除了还会再次同步么？

**Comment by labulakalia** [comment]
不会，后面的话准备加个选项来控制是否运行的时候同步所有已经存在的文章
