### ISSUE TITLE
无法正确同步语雀文章中开头写的frontmatter

### ISSUE THREAD

**Issue by TomatoFryEggs** [labulaka521/yuque_sync#4]

**Comment by labulakalia** [comment]
能提供点详细的信息吗？

**Comment by TomatoFryEggs** [comment]
> 能提供点详细的信息吗？

<img width="615" alt="image" src="https://user-images.githubusercontent.com/9395814/73431922-84b9db80-437c-11ea-820e-7f7f5d507193.png">
就像这样，我写在语雀的文章开头，同步后写在markdown文件开头

**Comment by labulakalia** [comment]
现在同步语雀的文章到markdown是自动生成这段的，在语雀中不需要填写，
现在自动生成的开头是这样的
```
---
title: "title"
date: "time"
draft: false
---
```
你有别的需求？

**Comment by TomatoFryEggs** [comment]
> 现在同步语雀的文章到markdown是自动生成这段的，在语雀中不需要填写，
> 现在自动生成的开头是这样的
> 
> ```
> ---
> title: "title"
> date: "time"
> draft: false
> ---
> ```
> 
> 你有别的需求？

对的，用于同步标签、创建时间、分类之类的，毕竟还是frontmatter详细，靠语雀的内置，一个个等，还是不太靠谱。

**Comment by labulakalia** [comment]
现在已经改成自适应，如果设置了frontmatter就不再生成
