### ISSUE TITLE
建议增加文章输出的自定义路径

### ISSUE THREAD

**Issue by timtangdev** [labulaka521/yuque_sync#5]
ls  ~/xx-blog/content
about.md  archives.md  images  **post**  ### posts

yuque_sync会把文章都输出到post，但是因为当前的主题一直以来都是在用posts这个目录来放文章，所以习惯性的就不想改之前的历史

**Comment by labulakalia** [comment]
可以，因为我之前的目录都在post，所以就设置成默认了

**Comment by labulakalia** [comment]
@dahvlh 已经将文章目录改为可配置
